name: moj_pipeline
on:
  pull_request:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2 
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests 
        run: npm test